Add validation to new client and edit client dialogs
ThePhilgrim/trans-calc pull request #10
Opened 2022-03-07 21:59 UTC by Akuli

I ended up doing quite a few changes. Let me know if you would prefer multiple smaller pull requests.

- No longer deals with the reversed order of `grid_slaves()`. Instead, there are `self.range_vars` and `self.discount_vars` lists which contain `StringVar` objects associated with the entries.
- `add_matrix_row()` and `delete_matrix_row()` were not used anywhere. I deleted them, because it would have taken a bit of effort to keep them up to date.
- Button is now disabled if you enter something invalid. Give it a try and let me know if you still hate disabled buttons.
- `client_full_rate_label` now has a `(required)` at the end, which prevents the user from wondering why the button is disabled. But the text looked funny when it was tall but not centered with the entries (the `n` sticky option). If you disagree, I'll add the `n`s back.

2022-03-08 18:08 UTC, ThePhilgrim reviewed
This looks good and makes a lot of sense.

I still don't like the way the disabled button is implemented. Or rather...

I am okay with having the button disabled, like right now. HOWEVER, it is not enough to disable the button. It needs to be complemented with some kind of message of exactly WHY it is disabled.

For example. If I put "FOO" in the full rate field and "BAR" in one of the matrix discount fields, the button is disabled.. I might not have seen the "(required)" because I can't really be bothered to read. I get no cues that the button is disabled, more than that nothing happens. So I think that maybe the program is broken. I then see the "ex. 0.15", and I change it to a float, thinking that "now it will definitely work", and then it's still disabled. Suddenly, I'm sure the program is broken.

Therefore, error messages are crucial here.


I would also prefer if you can't save the client unless you have added a client name.

2022-03-08 18:08 UTC, ThePhilgrim commented on trans-calc.py
>          self.client_currency_entry.delete(0, "end")
Shouldn't these also be set to `""` instead of being deleted?

2022-03-08 18:08 UTC, ThePhilgrim commented on trans-calc.py
>          self.client_currency_entry.insert(0, self.client_dict[self.currently_selected_client]["currency"])
Follow-up from previous comment. If yes, these should be `.set()`

2022-03-08 18:58 UTC, Akuli commented on trans-calc.py
>          self.client_currency_entry.delete(0, "end")
Entries have `delete` and `insert`. StringVars have `set`. Currently some of the entries use a StringVar, but not all of them do.

2022-03-08 18:58 UTC, Akuli commented
There is now a red error message label near the grayed-out button. It also shows an error if you try to leave the name field blank.

2022-03-08 19:44 UTC, ThePhilgrim requested changes

2022-03-08 19:44 UTC, ThePhilgrim commented on trans-calc.py
> +                    raise ValueError("Discount must be an integer.")
```suggestion
                    raise ValueError("Discount must be a percentage (0-100).")
```

2022-03-08 20:49 UTC, Akuli commented
Try it now :)

2022-03-09 18:57 UTC, ThePhilgrim reviewed
@Akuli 
1. I guess you misunderstood me yesterday. I didn't intend that the red entries substitute the error messages, but that when it's about the matrix, you get both. The reason for the red entries was because you said "If there is an error in the matrix, how will the user know which entry is the problematic one". I meant that the relevant entry can then be highlighted in addition to giving the error message.

2. After the latest commit, I get neither highlighted entries or error messages. When I click the save button with an entry with invalid data, nothing happens at all.

2022-03-10 08:53 UTC, Akuli commented
Apparently it isn't possible to make entries red on MacOS, which doesn't surprise me. I have noticed similar things with Tk and MacOS in the past.

Instead of coloring the entries, I made the error message not become red if you're missing a field. This way, you will still get the error when filling out the entries, but it isn't red and it shouldn't be at all annoying.

2023-07-07 15:16 UTC, ThePhilgrim commented
So, after thinking about this very very hard for 1 year and 4 months, I am finally very happy to merge this PR :D

2023-07-07 15:17 UTC, merged